USE [master]
GO
/****** Object:  Database [YGC]    Script Date: 6/11/2023 3:18:10 PM ******/
CREATE DATABASE [YGC]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'YGC', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\YGC.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'YGC_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\YGC_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [YGC] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [YGC].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [YGC] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [YGC] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [YGC] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [YGC] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [YGC] SET ARITHABORT OFF 
GO
ALTER DATABASE [YGC] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [YGC] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [YGC] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [YGC] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [YGC] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [YGC] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [YGC] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [YGC] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [YGC] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [YGC] SET  ENABLE_BROKER 
GO
ALTER DATABASE [YGC] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [YGC] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [YGC] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [YGC] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [YGC] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [YGC] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [YGC] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [YGC] SET RECOVERY FULL 
GO
ALTER DATABASE [YGC] SET  MULTI_USER 
GO
ALTER DATABASE [YGC] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [YGC] SET DB_CHAINING OFF 
GO
ALTER DATABASE [YGC] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [YGC] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [YGC] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'YGC', N'ON'
GO
ALTER DATABASE [YGC] SET QUERY_STORE = OFF
GO
USE [YGC]
GO
/****** Object:  Table [dbo].[AvailableDate]    Script Date: 6/11/2023 3:18:10 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AvailableDate](
	[lecturer_id] [int] NULL,
	[date] [datetime] NULL,
	[slot_id] [int] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Class]    Script Date: 6/11/2023 3:18:10 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Class](
	[class_id] [int] IDENTITY(1,1) NOT NULL,
	[class_name] [nvarchar](255) NOT NULL,
	[start_date] [datetime2](7) NOT NULL,
	[end_date] [datetime2](7) NOT NULL,
	[lecturer_id] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[class_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DateOfWeek]    Script Date: 6/11/2023 3:18:10 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DateOfWeek](
	[day_id] [int] IDENTITY(1,1) NOT NULL,
	[day] [varchar](30) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[day_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Enrollment]    Script Date: 6/11/2023 3:18:10 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Enrollment](
	[student_id] [int] NOT NULL,
	[class_id] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[student_id] ASC,
	[class_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Feedback]    Script Date: 6/11/2023 3:18:10 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Feedback](
	[feedback_id] [int] IDENTITY(1,1) NOT NULL,
	[time] [datetime2](7) NULL,
	[content] [nvarchar](255) NULL,
	[student_id] [int] NULL,
	[lecturer_id] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[feedback_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Payment]    Script Date: 6/11/2023 3:18:10 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Payment](
	[payment_id] [int] IDENTITY(1,1) NOT NULL,
	[student_id] [int] NULL,
	[amount] [money] NOT NULL,
	[method] [nvarchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[payment_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Roles]    Script Date: 6/11/2023 3:18:10 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Roles](
	[role_id] [int] IDENTITY(1,1) NOT NULL,
	[role_name] [varchar](20) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[role_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Schedule]    Script Date: 6/11/2023 3:18:10 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Schedule](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[class_id] [int] NULL,
	[slot_id] [int] NULL,
	[date] [datetime2](7) NOT NULL,
	[daily_note] [nvarchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[StudySlot]    Script Date: 6/11/2023 3:18:10 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[StudySlot](
	[slot_id] [int] IDENTITY(1,1) NOT NULL,
	[start_time] [time](7) NOT NULL,
	[end_time] [time](7) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[slot_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[StudySlotDay]    Script Date: 6/11/2023 3:18:10 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[StudySlotDay](
	[slot_id] [int] NOT NULL,
	[day_id] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[slot_id] ASC,
	[day_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 6/11/2023 3:18:10 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[uid] [int] IDENTITY(1,1) NOT NULL,
	[user_name] [varchar](50) NOT NULL,
	[password] [varchar](500) NOT NULL,
	[full_name] [nvarchar](50) NOT NULL,
	[address] [nvarchar](150) NULL,
	[phone] [varchar](12) NULL,
	[role_id] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[uid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AvailableDate]  WITH CHECK ADD FOREIGN KEY([lecturer_id])
REFERENCES [dbo].[Users] ([uid])
GO
ALTER TABLE [dbo].[AvailableDate]  WITH CHECK ADD FOREIGN KEY([slot_id])
REFERENCES [dbo].[StudySlot] ([slot_id])
GO
ALTER TABLE [dbo].[Class]  WITH CHECK ADD FOREIGN KEY([lecturer_id])
REFERENCES [dbo].[Users] ([uid])
GO
ALTER TABLE [dbo].[Enrollment]  WITH CHECK ADD FOREIGN KEY([class_id])
REFERENCES [dbo].[Class] ([class_id])
GO
ALTER TABLE [dbo].[Enrollment]  WITH CHECK ADD FOREIGN KEY([student_id])
REFERENCES [dbo].[Users] ([uid])
GO
ALTER TABLE [dbo].[Feedback]  WITH CHECK ADD FOREIGN KEY([lecturer_id])
REFERENCES [dbo].[Users] ([uid])
GO
ALTER TABLE [dbo].[Feedback]  WITH CHECK ADD FOREIGN KEY([student_id])
REFERENCES [dbo].[Users] ([uid])
GO
ALTER TABLE [dbo].[Payment]  WITH CHECK ADD FOREIGN KEY([student_id])
REFERENCES [dbo].[Users] ([uid])
GO
ALTER TABLE [dbo].[Schedule]  WITH CHECK ADD FOREIGN KEY([class_id])
REFERENCES [dbo].[Class] ([class_id])
GO
ALTER TABLE [dbo].[Schedule]  WITH CHECK ADD FOREIGN KEY([slot_id])
REFERENCES [dbo].[StudySlot] ([slot_id])
GO
ALTER TABLE [dbo].[StudySlotDay]  WITH CHECK ADD FOREIGN KEY([day_id])
REFERENCES [dbo].[DateOfWeek] ([day_id])
GO
ALTER TABLE [dbo].[StudySlotDay]  WITH CHECK ADD FOREIGN KEY([slot_id])
REFERENCES [dbo].[StudySlot] ([slot_id])
GO
ALTER TABLE [dbo].[Users]  WITH CHECK ADD FOREIGN KEY([role_id])
REFERENCES [dbo].[Roles] ([role_id])
GO
USE [master]
GO
ALTER DATABASE [YGC] SET  READ_WRITE 
GO
